---
- hosts: all
  become: true
  tasks:
  - name: Install httpd (apache) and php-fpm packages for AlmaLinux
    dnf:
      name: 
        - httpd
        - php-fpm
      state: latest
      update_cache: yes
    when: ansible_distribution == 'AlmaLinux'
    
  - name: Install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

 