---
- hosts: all
  become: true
  pre_tasks:
  #tasks:
    - name: Install updates - Almalinux node1
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == 'AlmaLinux'

    - name: Install updates - Ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

- hosts: web_servers
  become: true
  tasks:
    - name: Install apache2 and php packages for Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == 'Ubuntu'

    - name: Install httpd (apache) and php-fpm packages for AlmaLinux
      dnf:
        name:
          - httpd
          - php-fpm
        state: latest
      when: ansible_distribution == 'AlmaLinux'
- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package in Ubuntu
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      
- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest

